ALTER TABLE animals ADD COLUMN notice_no TEXT;
ALTER TABLE animals ADD COLUMN reg_no TEXT;
ALTER TABLE animals ADD COLUMN breed TEXT;
ALTER TABLE animals ADD COLUMN sex TEXT;
ALTER TABLE animals ADD COLUMN color TEXT;
ALTER TABLE animals ADD COLUMN neutered TEXT;
ALTER TABLE animals ADD COLUMN age_text TEXT;
ALTER TABLE animals ADD COLUMN age_bucket TEXT;
ALTER TABLE animals ADD COLUMN weight_kg REAL;
ALTER TABLE animals ADD COLUMN feature_rescue TEXT;
ALTER TABLE animals ADD COLUMN feature_social TEXT;
ALTER TABLE animals ADD COLUMN feature_health TEXT;
ALTER TABLE animals ADD COLUMN medical_check TEXT;
ALTER TABLE animals ADD COLUMN vaccination_status TEXT;
ALTER TABLE animals ADD COLUMN found_place TEXT;
ALTER TABLE animals ADD COLUMN received_at TEXT;
ALTER TABLE animals ADD COLUMN remarks TEXT;
ALTER TABLE animals ADD COLUMN jurisdiction TEXT;
ALTER TABLE animals ADD COLUMN status TEXT;
ALTER TABLE animals ADD COLUMN shelter_name TEXT;
ALTER TABLE animals ADD COLUMN shelter_place TEXT;
ALTER TABLE animals ADD COLUMN shelter_phone TEXT;
ALTER TABLE animals ADD COLUMN adoption_process TEXT;
ALTER TABLE animals ADD COLUMN adoption_support TEXT;
ALTER TABLE animals ADD COLUMN volunteer_info TEXT;
ALTER TABLE animals ADD COLUMN events_info TEXT;
ALTER TABLE animals ADD COLUMN photo_url TEXT;

CREATE INDEX IF NOT EXISTS idx_animals_status ON animals(status);
CREATE INDEX IF NOT EXISTS idx_animals_sex ON animals(sex);
CREATE INDEX IF NOT EXISTS idx_animals_age_bucket ON animals(age_bucket);
CREATE INDEX IF NOT EXISTS idx_animals_found_place ON animals(found_place);
CREATE INDEX IF NOT EXISTS idx_animals_shelter_name ON animals(shelter_name);
